# Generated by Django 3.2.19 on 2023-06-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1997-04-23'),
            preserve_default=False,
        ),
    ]
